# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: my_message.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

class _runtime_version:
    class Domain:
        PUBLIC = 0
    @staticmethod
    def ValidateProtobufRuntimeVersion(*args, **kwargs):
        return True

_runtime_version.ValidateProtobufRuntimeVersion()

_sym_db = _symbol_database.Default()

# এখানে বাইনারি ডেটার ভেতর '\tMyMessage' সরিয়ে '\x06RAFIN' বসানো হয়েছে (দৈর্ঘ্য ৯ থেকে ৬ করা হয়েছে)
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10my_message.proto\">\n\x06RAFIN\x12\x0f\n\x07\x66ield21\x18\x15 \x01(\x03\x12\x0f\n\x07\x66ield22\x18\x16 \x01(\x0c\x12\x0f\n\x07\x66ield23\x18\x17 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  # ক্লাসের নাম ও এন্ড অফসেট (৮২ থেকে ৭৯) নাম অনুযায়ী ঠিক করা হয়েছে
  _globals['_RAFIN']._serialized_start=20
  _globals['_RAFIN']._serialized_end=79